<?php

namespace AppBundle\Repository;

/**
 * blockContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class blockContentRepository extends \Doctrine\ORM\EntityRepository
{
}
